# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Ethernet

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EthernetStatus(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EthernetStatus()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEthernetStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EthernetStatusBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x49\x45\x4E", size_prefixed=size_prefixed)

    # EthernetStatus
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EthernetStatus
    def Sync(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(1)
def EthernetStatusStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddSync(builder, sync): builder.PrependInt8Slot(0, sync, 0)
def EthernetStatusAddSync(builder, sync):
    """This method is deprecated. Please switch to AddSync."""
    return AddSync(builder, sync)
def End(builder): return builder.EndObject()
def EthernetStatusEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)