#ifndef CAN_VERIFIER_H
#define CAN_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef CAN_READER_H
#include "can_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int AutomotiveBus_Register_Can_CanStatus_verify_table(flatcc_table_verifier_descriptor_t *td);
static int AutomotiveBus_Register_Can_Frame_verify_table(flatcc_table_verifier_descriptor_t *td);
static int AutomotiveBus_Register_Can_MetaFrame_verify_table(flatcc_table_verifier_descriptor_t *td);
static int AutomotiveBus_Register_Can_RegisterFile_verify_table(flatcc_table_verifier_descriptor_t *td);

static inline int AutomotiveBus_Register_Can_TimeSpec_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, AutomotiveBus_Register_Can_TimeSpec_identifier, 8, 8);
}

static inline int AutomotiveBus_Register_Can_TimeSpec_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, AutomotiveBus_Register_Can_TimeSpec_type_hash, 8, 8);
}

static inline int AutomotiveBus_Register_Can_TimeSpec_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 8);
}

static inline int AutomotiveBus_Register_Can_TimeSpec_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 8);
}

static inline int AutomotiveBus_Register_Can_MessageTiming_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, AutomotiveBus_Register_Can_MessageTiming_identifier, 24, 8);
}

static inline int AutomotiveBus_Register_Can_MessageTiming_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, AutomotiveBus_Register_Can_MessageTiming_type_hash, 24, 8);
}

static inline int AutomotiveBus_Register_Can_MessageTiming_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 24, 8);
}

static inline int AutomotiveBus_Register_Can_MessageTiming_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 24, 8);
}

static int AutomotiveBus_Register_Can_CanStatus_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* sync */)) return ret;
    return flatcc_verify_ok;
}

static inline int AutomotiveBus_Register_Can_CanStatus_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, AutomotiveBus_Register_Can_CanStatus_identifier, &AutomotiveBus_Register_Can_CanStatus_verify_table);
}

static inline int AutomotiveBus_Register_Can_CanStatus_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, AutomotiveBus_Register_Can_CanStatus_type_identifier, &AutomotiveBus_Register_Can_CanStatus_verify_table);
}

static inline int AutomotiveBus_Register_Can_CanStatus_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &AutomotiveBus_Register_Can_CanStatus_verify_table);
}

static inline int AutomotiveBus_Register_Can_CanStatus_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &AutomotiveBus_Register_Can_CanStatus_verify_table);
}

static int AutomotiveBus_Register_Can_Frame_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* frame_id */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 0, 1, 1, INT64_C(4294967295)) /* payload */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 1, 1) /* length */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* rtr */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 1, 1) /* frame_type */)) return ret;
    return flatcc_verify_ok;
}

static inline int AutomotiveBus_Register_Can_Frame_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, AutomotiveBus_Register_Can_Frame_identifier, &AutomotiveBus_Register_Can_Frame_verify_table);
}

static inline int AutomotiveBus_Register_Can_Frame_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, AutomotiveBus_Register_Can_Frame_type_identifier, &AutomotiveBus_Register_Can_Frame_verify_table);
}

static inline int AutomotiveBus_Register_Can_Frame_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &AutomotiveBus_Register_Can_Frame_verify_table);
}

static inline int AutomotiveBus_Register_Can_Frame_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &AutomotiveBus_Register_Can_Frame_verify_table);
}

static int AutomotiveBus_Register_Can_MetaFrame_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* status */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* direction */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 1, 1) /* can_fd_enabled */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 3, 0, &AutomotiveBus_Register_Can_Frame_verify_table) /* frame */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 24, 8) /* timing */)) return ret;
    return flatcc_verify_ok;
}

static inline int AutomotiveBus_Register_Can_MetaFrame_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, AutomotiveBus_Register_Can_MetaFrame_identifier, &AutomotiveBus_Register_Can_MetaFrame_verify_table);
}

static inline int AutomotiveBus_Register_Can_MetaFrame_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, AutomotiveBus_Register_Can_MetaFrame_type_identifier, &AutomotiveBus_Register_Can_MetaFrame_verify_table);
}

static inline int AutomotiveBus_Register_Can_MetaFrame_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &AutomotiveBus_Register_Can_MetaFrame_verify_table);
}

static inline int AutomotiveBus_Register_Can_MetaFrame_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &AutomotiveBus_Register_Can_MetaFrame_verify_table);
}

static int AutomotiveBus_Register_Can_RegisterFile_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &AutomotiveBus_Register_Can_MetaFrame_verify_table) /* buffer */)) return ret;
    return flatcc_verify_ok;
}

static inline int AutomotiveBus_Register_Can_RegisterFile_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, AutomotiveBus_Register_Can_RegisterFile_identifier, &AutomotiveBus_Register_Can_RegisterFile_verify_table);
}

static inline int AutomotiveBus_Register_Can_RegisterFile_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, AutomotiveBus_Register_Can_RegisterFile_type_identifier, &AutomotiveBus_Register_Can_RegisterFile_verify_table);
}

static inline int AutomotiveBus_Register_Can_RegisterFile_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &AutomotiveBus_Register_Can_RegisterFile_verify_table);
}

static inline int AutomotiveBus_Register_Can_RegisterFile_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &AutomotiveBus_Register_Can_RegisterFile_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* CAN_VERIFIER_H */
