# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Channel

class MessageType(object):
    NONE = 0
    SignalWrite = 1
    SignalRead = 2
    SignalValue = 3
    SignalIndex = 4

