# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlexRay

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TimeSpec(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # TimeSpec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TimeSpec
    def Psec10(self): return self._tab.Get(flatbuffers.number_types.Int64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateTimeSpec(builder, psec10):
    builder.Prep(8, 8)
    builder.PrependInt64(psec10)
    return builder.Offset()
