#ifndef PDU_BUILDER_H
#define PDU_BUILDER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef PDU_READER_H
#include "pdu_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "SPDU"
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif

#define __AutomotiveBus_Stream_Pdu_CanMessageFormat_formal_args , AutomotiveBus_Stream_Pdu_CanMessageFormat_enum_t v0
#define __AutomotiveBus_Stream_Pdu_CanMessageFormat_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, AutomotiveBus_Stream_Pdu_CanMessageFormat, AutomotiveBus_Stream_Pdu_CanMessageFormat_enum_t)
#define __AutomotiveBus_Stream_Pdu_CanFrameType_formal_args , AutomotiveBus_Stream_Pdu_CanFrameType_enum_t v0
#define __AutomotiveBus_Stream_Pdu_CanFrameType_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, AutomotiveBus_Stream_Pdu_CanFrameType, AutomotiveBus_Stream_Pdu_CanFrameType_enum_t)
#define __AutomotiveBus_Stream_Pdu_IpProtocol_formal_args , AutomotiveBus_Stream_Pdu_IpProtocol_enum_t v0
#define __AutomotiveBus_Stream_Pdu_IpProtocol_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, AutomotiveBus_Stream_Pdu_IpProtocol, AutomotiveBus_Stream_Pdu_IpProtocol_enum_t)

#define __AutomotiveBus_Stream_Pdu_IpAddressV6_formal_args ,\
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,\
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7
#define __AutomotiveBus_Stream_Pdu_IpAddressV6_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7
static inline AutomotiveBus_Stream_Pdu_IpAddressV6_t *AutomotiveBus_Stream_Pdu_IpAddressV6_assign(AutomotiveBus_Stream_Pdu_IpAddressV6_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7)
{ p->v0 = v0; p->v1 = v1; p->v2 = v2; p->v3 = v3;
  p->v4 = v4; p->v5 = v5; p->v6 = v6; p->v7 = v7;
  return p; }
static inline AutomotiveBus_Stream_Pdu_IpAddressV6_t *AutomotiveBus_Stream_Pdu_IpAddressV6_copy(AutomotiveBus_Stream_Pdu_IpAddressV6_t *p, const AutomotiveBus_Stream_Pdu_IpAddressV6_t *p2)
{ p->v0 = p2->v0; p->v1 = p2->v1; p->v2 = p2->v2; p->v3 = p2->v3;
  p->v4 = p2->v4; p->v5 = p2->v5; p->v6 = p2->v6; p->v7 = p2->v7;
  return p; }
static inline AutomotiveBus_Stream_Pdu_IpAddressV6_t *AutomotiveBus_Stream_Pdu_IpAddressV6_assign_to_pe(AutomotiveBus_Stream_Pdu_IpAddressV6_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7)
{ flatbuffers_uint16_assign_to_pe(&p->v0, v0); flatbuffers_uint16_assign_to_pe(&p->v1, v1); flatbuffers_uint16_assign_to_pe(&p->v2, v2); flatbuffers_uint16_assign_to_pe(&p->v3, v3);
  flatbuffers_uint16_assign_to_pe(&p->v4, v4); flatbuffers_uint16_assign_to_pe(&p->v5, v5); flatbuffers_uint16_assign_to_pe(&p->v6, v6); flatbuffers_uint16_assign_to_pe(&p->v7, v7);
  return p; }
static inline AutomotiveBus_Stream_Pdu_IpAddressV6_t *AutomotiveBus_Stream_Pdu_IpAddressV6_copy_to_pe(AutomotiveBus_Stream_Pdu_IpAddressV6_t *p, const AutomotiveBus_Stream_Pdu_IpAddressV6_t *p2)
{ flatbuffers_uint16_copy_to_pe(&p->v0, &p2->v0); flatbuffers_uint16_copy_to_pe(&p->v1, &p2->v1); flatbuffers_uint16_copy_to_pe(&p->v2, &p2->v2); flatbuffers_uint16_copy_to_pe(&p->v3, &p2->v3);
  flatbuffers_uint16_copy_to_pe(&p->v4, &p2->v4); flatbuffers_uint16_copy_to_pe(&p->v5, &p2->v5); flatbuffers_uint16_copy_to_pe(&p->v6, &p2->v6); flatbuffers_uint16_copy_to_pe(&p->v7, &p2->v7);
  return p; }
static inline AutomotiveBus_Stream_Pdu_IpAddressV6_t *AutomotiveBus_Stream_Pdu_IpAddressV6_assign_from_pe(AutomotiveBus_Stream_Pdu_IpAddressV6_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7)
{ flatbuffers_uint16_assign_from_pe(&p->v0, v0); flatbuffers_uint16_assign_from_pe(&p->v1, v1); flatbuffers_uint16_assign_from_pe(&p->v2, v2); flatbuffers_uint16_assign_from_pe(&p->v3, v3);
  flatbuffers_uint16_assign_from_pe(&p->v4, v4); flatbuffers_uint16_assign_from_pe(&p->v5, v5); flatbuffers_uint16_assign_from_pe(&p->v6, v6); flatbuffers_uint16_assign_from_pe(&p->v7, v7);
  return p; }
static inline AutomotiveBus_Stream_Pdu_IpAddressV6_t *AutomotiveBus_Stream_Pdu_IpAddressV6_copy_from_pe(AutomotiveBus_Stream_Pdu_IpAddressV6_t *p, const AutomotiveBus_Stream_Pdu_IpAddressV6_t *p2)
{ flatbuffers_uint16_copy_from_pe(&p->v0, &p2->v0); flatbuffers_uint16_copy_from_pe(&p->v1, &p2->v1); flatbuffers_uint16_copy_from_pe(&p->v2, &p2->v2); flatbuffers_uint16_copy_from_pe(&p->v3, &p2->v3);
  flatbuffers_uint16_copy_from_pe(&p->v4, &p2->v4); flatbuffers_uint16_copy_from_pe(&p->v5, &p2->v5); flatbuffers_uint16_copy_from_pe(&p->v6, &p2->v6); flatbuffers_uint16_copy_from_pe(&p->v7, &p2->v7);
  return p; }
__flatbuffers_build_struct(flatbuffers_, AutomotiveBus_Stream_Pdu_IpAddressV6, 16, 2, AutomotiveBus_Stream_Pdu_IpAddressV6_identifier, AutomotiveBus_Stream_Pdu_IpAddressV6_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, AutomotiveBus_Stream_Pdu_IpAddressV6, AutomotiveBus_Stream_Pdu_IpAddressV6_t)

typedef flatbuffers_union_ref_t AutomotiveBus_Stream_Pdu_SocketAdapter_union_ref_t;
typedef flatbuffers_union_vec_ref_t AutomotiveBus_Stream_Pdu_SocketAdapter_union_vec_ref_t;
static AutomotiveBus_Stream_Pdu_SocketAdapter_union_ref_t AutomotiveBus_Stream_Pdu_SocketAdapter_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_SocketAdapter_union_t t);
typedef flatbuffers_union_ref_t AutomotiveBus_Stream_Pdu_IpAddr_union_ref_t;
typedef flatbuffers_union_vec_ref_t AutomotiveBus_Stream_Pdu_IpAddr_union_vec_ref_t;
static AutomotiveBus_Stream_Pdu_IpAddr_union_ref_t AutomotiveBus_Stream_Pdu_IpAddr_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_IpAddr_union_t t);
typedef flatbuffers_union_ref_t AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t;
typedef flatbuffers_union_vec_ref_t AutomotiveBus_Stream_Pdu_TransportMetadata_union_vec_ref_t;
static AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t AutomotiveBus_Stream_Pdu_TransportMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_TransportMetadata_union_t t);

static const flatbuffers_voffset_t __AutomotiveBus_Stream_Pdu_CanMessageMetadata_required[] = { 0 };
typedef flatbuffers_ref_t AutomotiveBus_Stream_Pdu_CanMessageMetadata_ref_t;
static AutomotiveBus_Stream_Pdu_CanMessageMetadata_ref_t AutomotiveBus_Stream_Pdu_CanMessageMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_CanMessageMetadata_table_t t);
__flatbuffers_build_table(flatbuffers_, AutomotiveBus_Stream_Pdu_CanMessageMetadata, 4)

static const flatbuffers_voffset_t __AutomotiveBus_Stream_Pdu_DoIpMetadata_required[] = { 0 };
typedef flatbuffers_ref_t AutomotiveBus_Stream_Pdu_DoIpMetadata_ref_t;
static AutomotiveBus_Stream_Pdu_DoIpMetadata_ref_t AutomotiveBus_Stream_Pdu_DoIpMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_DoIpMetadata_table_t t);
__flatbuffers_build_table(flatbuffers_, AutomotiveBus_Stream_Pdu_DoIpMetadata, 2)

static const flatbuffers_voffset_t __AutomotiveBus_Stream_Pdu_SomeIpMetadata_required[] = { 0 };
typedef flatbuffers_ref_t AutomotiveBus_Stream_Pdu_SomeIpMetadata_ref_t;
static AutomotiveBus_Stream_Pdu_SomeIpMetadata_ref_t AutomotiveBus_Stream_Pdu_SomeIpMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_SomeIpMetadata_table_t t);
__flatbuffers_build_table(flatbuffers_, AutomotiveBus_Stream_Pdu_SomeIpMetadata, 7)

static const flatbuffers_voffset_t __AutomotiveBus_Stream_Pdu_IpV4_required[] = { 0 };
typedef flatbuffers_ref_t AutomotiveBus_Stream_Pdu_IpV4_ref_t;
static AutomotiveBus_Stream_Pdu_IpV4_ref_t AutomotiveBus_Stream_Pdu_IpV4_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_IpV4_table_t t);
__flatbuffers_build_table(flatbuffers_, AutomotiveBus_Stream_Pdu_IpV4, 2)

static const flatbuffers_voffset_t __AutomotiveBus_Stream_Pdu_IpV6_required[] = { 0 };
typedef flatbuffers_ref_t AutomotiveBus_Stream_Pdu_IpV6_ref_t;
static AutomotiveBus_Stream_Pdu_IpV6_ref_t AutomotiveBus_Stream_Pdu_IpV6_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_IpV6_table_t t);
__flatbuffers_build_table(flatbuffers_, AutomotiveBus_Stream_Pdu_IpV6, 2)

static const flatbuffers_voffset_t __AutomotiveBus_Stream_Pdu_IpMessageMetadata_required[] = { 0 };
typedef flatbuffers_ref_t AutomotiveBus_Stream_Pdu_IpMessageMetadata_ref_t;
static AutomotiveBus_Stream_Pdu_IpMessageMetadata_ref_t AutomotiveBus_Stream_Pdu_IpMessageMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_IpMessageMetadata_table_t t);
__flatbuffers_build_table(flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata, 13)

static const flatbuffers_voffset_t __AutomotiveBus_Stream_Pdu_StructMetadata_required[] = { 0 };
typedef flatbuffers_ref_t AutomotiveBus_Stream_Pdu_StructMetadata_ref_t;
static AutomotiveBus_Stream_Pdu_StructMetadata_ref_t AutomotiveBus_Stream_Pdu_StructMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_StructMetadata_table_t t);
__flatbuffers_build_table(flatbuffers_, AutomotiveBus_Stream_Pdu_StructMetadata, 8)

static const flatbuffers_voffset_t __AutomotiveBus_Stream_Pdu_Pdu_required[] = { 0 };
typedef flatbuffers_ref_t AutomotiveBus_Stream_Pdu_Pdu_ref_t;
static AutomotiveBus_Stream_Pdu_Pdu_ref_t AutomotiveBus_Stream_Pdu_Pdu_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_Pdu_table_t t);
__flatbuffers_build_table(flatbuffers_, AutomotiveBus_Stream_Pdu_Pdu, 6)

static const flatbuffers_voffset_t __AutomotiveBus_Stream_Pdu_Stream_required[] = { 0 };
typedef flatbuffers_ref_t AutomotiveBus_Stream_Pdu_Stream_ref_t;
static AutomotiveBus_Stream_Pdu_Stream_ref_t AutomotiveBus_Stream_Pdu_Stream_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_Stream_table_t t);
__flatbuffers_build_table(flatbuffers_, AutomotiveBus_Stream_Pdu_Stream, 2)

#define __AutomotiveBus_Stream_Pdu_CanMessageMetadata_formal_args , AutomotiveBus_Stream_Pdu_CanMessageFormat_enum_t v0, AutomotiveBus_Stream_Pdu_CanFrameType_enum_t v1, uint32_t v2, uint32_t v3
#define __AutomotiveBus_Stream_Pdu_CanMessageMetadata_call_args , v0, v1, v2, v3
static inline AutomotiveBus_Stream_Pdu_CanMessageMetadata_ref_t AutomotiveBus_Stream_Pdu_CanMessageMetadata_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_CanMessageMetadata_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, AutomotiveBus_Stream_Pdu_CanMessageMetadata, AutomotiveBus_Stream_Pdu_CanMessageMetadata_identifier, AutomotiveBus_Stream_Pdu_CanMessageMetadata_type_identifier)

#define __AutomotiveBus_Stream_Pdu_DoIpMetadata_formal_args , uint8_t v0, uint16_t v1
#define __AutomotiveBus_Stream_Pdu_DoIpMetadata_call_args , v0, v1
static inline AutomotiveBus_Stream_Pdu_DoIpMetadata_ref_t AutomotiveBus_Stream_Pdu_DoIpMetadata_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_DoIpMetadata_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, AutomotiveBus_Stream_Pdu_DoIpMetadata, AutomotiveBus_Stream_Pdu_DoIpMetadata_identifier, AutomotiveBus_Stream_Pdu_DoIpMetadata_type_identifier)

#define __AutomotiveBus_Stream_Pdu_SomeIpMetadata_formal_args ,\
  uint32_t v0, uint32_t v1, uint32_t v2, uint8_t v3,\
  uint8_t v4, uint8_t v5, uint8_t v6
#define __AutomotiveBus_Stream_Pdu_SomeIpMetadata_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6
static inline AutomotiveBus_Stream_Pdu_SomeIpMetadata_ref_t AutomotiveBus_Stream_Pdu_SomeIpMetadata_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_SomeIpMetadata_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, AutomotiveBus_Stream_Pdu_SomeIpMetadata, AutomotiveBus_Stream_Pdu_SomeIpMetadata_identifier, AutomotiveBus_Stream_Pdu_SomeIpMetadata_type_identifier)

#define __AutomotiveBus_Stream_Pdu_IpV4_formal_args , uint32_t v0, uint32_t v1
#define __AutomotiveBus_Stream_Pdu_IpV4_call_args , v0, v1
static inline AutomotiveBus_Stream_Pdu_IpV4_ref_t AutomotiveBus_Stream_Pdu_IpV4_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_IpV4_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, AutomotiveBus_Stream_Pdu_IpV4, AutomotiveBus_Stream_Pdu_IpV4_identifier, AutomotiveBus_Stream_Pdu_IpV4_type_identifier)

#define __AutomotiveBus_Stream_Pdu_IpV6_formal_args , AutomotiveBus_Stream_Pdu_IpAddressV6_t *v0, AutomotiveBus_Stream_Pdu_IpAddressV6_t *v1
#define __AutomotiveBus_Stream_Pdu_IpV6_call_args , v0, v1
static inline AutomotiveBus_Stream_Pdu_IpV6_ref_t AutomotiveBus_Stream_Pdu_IpV6_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_IpV6_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, AutomotiveBus_Stream_Pdu_IpV6, AutomotiveBus_Stream_Pdu_IpV6_identifier, AutomotiveBus_Stream_Pdu_IpV6_type_identifier)

#define __AutomotiveBus_Stream_Pdu_IpMessageMetadata_formal_args ,\
  uint64_t v0, uint64_t v1, uint16_t v2, uint8_t v3,\
  uint8_t v4, uint16_t v5, AutomotiveBus_Stream_Pdu_IpAddr_union_ref_t v7, AutomotiveBus_Stream_Pdu_IpProtocol_enum_t v8,\
  uint16_t v9, uint16_t v10, AutomotiveBus_Stream_Pdu_SocketAdapter_union_ref_t v12
#define __AutomotiveBus_Stream_Pdu_IpMessageMetadata_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v7, v8,\
  v9, v10, v12
static inline AutomotiveBus_Stream_Pdu_IpMessageMetadata_ref_t AutomotiveBus_Stream_Pdu_IpMessageMetadata_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_IpMessageMetadata_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata, AutomotiveBus_Stream_Pdu_IpMessageMetadata_identifier, AutomotiveBus_Stream_Pdu_IpMessageMetadata_type_identifier)

#define __AutomotiveBus_Stream_Pdu_StructMetadata_formal_args ,\
  flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1, flatbuffers_string_ref_t v2, uint16_t v3,\
  flatbuffers_bool_t v4, flatbuffers_string_ref_t v5, flatbuffers_string_ref_t v6, flatbuffers_string_ref_t v7
#define __AutomotiveBus_Stream_Pdu_StructMetadata_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7
static inline AutomotiveBus_Stream_Pdu_StructMetadata_ref_t AutomotiveBus_Stream_Pdu_StructMetadata_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_StructMetadata_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, AutomotiveBus_Stream_Pdu_StructMetadata, AutomotiveBus_Stream_Pdu_StructMetadata_identifier, AutomotiveBus_Stream_Pdu_StructMetadata_type_identifier)

#define __AutomotiveBus_Stream_Pdu_Pdu_formal_args ,\
  uint32_t v0, flatbuffers_uint8_vec_ref_t v1, AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t v3, uint32_t v4, uint32_t v5
#define __AutomotiveBus_Stream_Pdu_Pdu_call_args ,\
  v0, v1, v3, v4, v5
static inline AutomotiveBus_Stream_Pdu_Pdu_ref_t AutomotiveBus_Stream_Pdu_Pdu_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_Pdu_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, AutomotiveBus_Stream_Pdu_Pdu, AutomotiveBus_Stream_Pdu_Pdu_identifier, AutomotiveBus_Stream_Pdu_Pdu_type_identifier)

#define __AutomotiveBus_Stream_Pdu_Stream_formal_args , AutomotiveBus_Stream_Pdu_Pdu_vec_ref_t v0, uint32_t v1
#define __AutomotiveBus_Stream_Pdu_Stream_call_args , v0, v1
static inline AutomotiveBus_Stream_Pdu_Stream_ref_t AutomotiveBus_Stream_Pdu_Stream_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_Stream_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, AutomotiveBus_Stream_Pdu_Stream, AutomotiveBus_Stream_Pdu_Stream_identifier, AutomotiveBus_Stream_Pdu_Stream_type_identifier)

static inline AutomotiveBus_Stream_Pdu_SocketAdapter_union_ref_t AutomotiveBus_Stream_Pdu_SocketAdapter_as_NONE()
{ AutomotiveBus_Stream_Pdu_SocketAdapter_union_ref_t uref; uref.type = AutomotiveBus_Stream_Pdu_SocketAdapter_NONE; uref.value = 0; return uref; }
static inline AutomotiveBus_Stream_Pdu_SocketAdapter_union_ref_t AutomotiveBus_Stream_Pdu_SocketAdapter_as_do_ip(AutomotiveBus_Stream_Pdu_DoIpMetadata_ref_t ref)
{ AutomotiveBus_Stream_Pdu_SocketAdapter_union_ref_t uref; uref.type = AutomotiveBus_Stream_Pdu_SocketAdapter_do_ip; uref.value = ref; return uref; }
static inline AutomotiveBus_Stream_Pdu_SocketAdapter_union_ref_t AutomotiveBus_Stream_Pdu_SocketAdapter_as_some_ip(AutomotiveBus_Stream_Pdu_SomeIpMetadata_ref_t ref)
{ AutomotiveBus_Stream_Pdu_SocketAdapter_union_ref_t uref; uref.type = AutomotiveBus_Stream_Pdu_SocketAdapter_some_ip; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, AutomotiveBus_Stream_Pdu_SocketAdapter)

static AutomotiveBus_Stream_Pdu_SocketAdapter_union_ref_t AutomotiveBus_Stream_Pdu_SocketAdapter_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_SocketAdapter_union_t u)
{
    switch (u.type) {
    case 1: return AutomotiveBus_Stream_Pdu_SocketAdapter_as_do_ip(AutomotiveBus_Stream_Pdu_DoIpMetadata_clone(B, (AutomotiveBus_Stream_Pdu_DoIpMetadata_table_t)u.value));
    case 2: return AutomotiveBus_Stream_Pdu_SocketAdapter_as_some_ip(AutomotiveBus_Stream_Pdu_SomeIpMetadata_clone(B, (AutomotiveBus_Stream_Pdu_SomeIpMetadata_table_t)u.value));
    default: return AutomotiveBus_Stream_Pdu_SocketAdapter_as_NONE();
    }
}

static inline AutomotiveBus_Stream_Pdu_IpAddr_union_ref_t AutomotiveBus_Stream_Pdu_IpAddr_as_NONE()
{ AutomotiveBus_Stream_Pdu_IpAddr_union_ref_t uref; uref.type = AutomotiveBus_Stream_Pdu_IpAddr_NONE; uref.value = 0; return uref; }
static inline AutomotiveBus_Stream_Pdu_IpAddr_union_ref_t AutomotiveBus_Stream_Pdu_IpAddr_as_v4(AutomotiveBus_Stream_Pdu_IpV4_ref_t ref)
{ AutomotiveBus_Stream_Pdu_IpAddr_union_ref_t uref; uref.type = AutomotiveBus_Stream_Pdu_IpAddr_v4; uref.value = ref; return uref; }
static inline AutomotiveBus_Stream_Pdu_IpAddr_union_ref_t AutomotiveBus_Stream_Pdu_IpAddr_as_v6(AutomotiveBus_Stream_Pdu_IpV6_ref_t ref)
{ AutomotiveBus_Stream_Pdu_IpAddr_union_ref_t uref; uref.type = AutomotiveBus_Stream_Pdu_IpAddr_v6; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, AutomotiveBus_Stream_Pdu_IpAddr)

static AutomotiveBus_Stream_Pdu_IpAddr_union_ref_t AutomotiveBus_Stream_Pdu_IpAddr_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_IpAddr_union_t u)
{
    switch (u.type) {
    case 1: return AutomotiveBus_Stream_Pdu_IpAddr_as_v4(AutomotiveBus_Stream_Pdu_IpV4_clone(B, (AutomotiveBus_Stream_Pdu_IpV4_table_t)u.value));
    case 2: return AutomotiveBus_Stream_Pdu_IpAddr_as_v6(AutomotiveBus_Stream_Pdu_IpV6_clone(B, (AutomotiveBus_Stream_Pdu_IpV6_table_t)u.value));
    default: return AutomotiveBus_Stream_Pdu_IpAddr_as_NONE();
    }
}

static inline AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t AutomotiveBus_Stream_Pdu_TransportMetadata_as_NONE()
{ AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t uref; uref.type = AutomotiveBus_Stream_Pdu_TransportMetadata_NONE; uref.value = 0; return uref; }
static inline AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t AutomotiveBus_Stream_Pdu_TransportMetadata_as_Can(AutomotiveBus_Stream_Pdu_CanMessageMetadata_ref_t ref)
{ AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t uref; uref.type = AutomotiveBus_Stream_Pdu_TransportMetadata_Can; uref.value = ref; return uref; }
static inline AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t AutomotiveBus_Stream_Pdu_TransportMetadata_as_Ip(AutomotiveBus_Stream_Pdu_IpMessageMetadata_ref_t ref)
{ AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t uref; uref.type = AutomotiveBus_Stream_Pdu_TransportMetadata_Ip; uref.value = ref; return uref; }
static inline AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t AutomotiveBus_Stream_Pdu_TransportMetadata_as_Struct(AutomotiveBus_Stream_Pdu_StructMetadata_ref_t ref)
{ AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t uref; uref.type = AutomotiveBus_Stream_Pdu_TransportMetadata_Struct; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, AutomotiveBus_Stream_Pdu_TransportMetadata)

static AutomotiveBus_Stream_Pdu_TransportMetadata_union_ref_t AutomotiveBus_Stream_Pdu_TransportMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_TransportMetadata_union_t u)
{
    switch (u.type) {
    case 1: return AutomotiveBus_Stream_Pdu_TransportMetadata_as_Can(AutomotiveBus_Stream_Pdu_CanMessageMetadata_clone(B, (AutomotiveBus_Stream_Pdu_CanMessageMetadata_table_t)u.value));
    case 2: return AutomotiveBus_Stream_Pdu_TransportMetadata_as_Ip(AutomotiveBus_Stream_Pdu_IpMessageMetadata_clone(B, (AutomotiveBus_Stream_Pdu_IpMessageMetadata_table_t)u.value));
    case 3: return AutomotiveBus_Stream_Pdu_TransportMetadata_as_Struct(AutomotiveBus_Stream_Pdu_StructMetadata_clone(B, (AutomotiveBus_Stream_Pdu_StructMetadata_table_t)u.value));
    default: return AutomotiveBus_Stream_Pdu_TransportMetadata_as_NONE();
    }
}

__flatbuffers_build_scalar_field(0, flatbuffers_, AutomotiveBus_Stream_Pdu_CanMessageMetadata_message_format, AutomotiveBus_Stream_Pdu_CanMessageFormat, AutomotiveBus_Stream_Pdu_CanMessageFormat_enum_t, 1, 1, INT8_C(0), AutomotiveBus_Stream_Pdu_CanMessageMetadata)
__flatbuffers_build_scalar_field(1, flatbuffers_, AutomotiveBus_Stream_Pdu_CanMessageMetadata_frame_type, AutomotiveBus_Stream_Pdu_CanFrameType, AutomotiveBus_Stream_Pdu_CanFrameType_enum_t, 1, 1, INT8_C(0), AutomotiveBus_Stream_Pdu_CanMessageMetadata)
__flatbuffers_build_scalar_field(2, flatbuffers_, AutomotiveBus_Stream_Pdu_CanMessageMetadata_interface_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), AutomotiveBus_Stream_Pdu_CanMessageMetadata)
__flatbuffers_build_scalar_field(3, flatbuffers_, AutomotiveBus_Stream_Pdu_CanMessageMetadata_network_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), AutomotiveBus_Stream_Pdu_CanMessageMetadata)

static inline AutomotiveBus_Stream_Pdu_CanMessageMetadata_ref_t AutomotiveBus_Stream_Pdu_CanMessageMetadata_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_CanMessageMetadata_formal_args)
{
    if (AutomotiveBus_Stream_Pdu_CanMessageMetadata_start(B)
        || AutomotiveBus_Stream_Pdu_CanMessageMetadata_interface_id_add(B, v2)
        || AutomotiveBus_Stream_Pdu_CanMessageMetadata_network_id_add(B, v3)
        || AutomotiveBus_Stream_Pdu_CanMessageMetadata_message_format_add(B, v0)
        || AutomotiveBus_Stream_Pdu_CanMessageMetadata_frame_type_add(B, v1)) {
        return 0;
    }
    return AutomotiveBus_Stream_Pdu_CanMessageMetadata_end(B);
}

static AutomotiveBus_Stream_Pdu_CanMessageMetadata_ref_t AutomotiveBus_Stream_Pdu_CanMessageMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_CanMessageMetadata_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (AutomotiveBus_Stream_Pdu_CanMessageMetadata_start(B)
        || AutomotiveBus_Stream_Pdu_CanMessageMetadata_interface_id_pick(B, t)
        || AutomotiveBus_Stream_Pdu_CanMessageMetadata_network_id_pick(B, t)
        || AutomotiveBus_Stream_Pdu_CanMessageMetadata_message_format_pick(B, t)
        || AutomotiveBus_Stream_Pdu_CanMessageMetadata_frame_type_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, AutomotiveBus_Stream_Pdu_CanMessageMetadata_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, AutomotiveBus_Stream_Pdu_DoIpMetadata_protocol_version, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), AutomotiveBus_Stream_Pdu_DoIpMetadata)
__flatbuffers_build_scalar_field(1, flatbuffers_, AutomotiveBus_Stream_Pdu_DoIpMetadata_payload_type, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), AutomotiveBus_Stream_Pdu_DoIpMetadata)

static inline AutomotiveBus_Stream_Pdu_DoIpMetadata_ref_t AutomotiveBus_Stream_Pdu_DoIpMetadata_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_DoIpMetadata_formal_args)
{
    if (AutomotiveBus_Stream_Pdu_DoIpMetadata_start(B)
        || AutomotiveBus_Stream_Pdu_DoIpMetadata_payload_type_add(B, v1)
        || AutomotiveBus_Stream_Pdu_DoIpMetadata_protocol_version_add(B, v0)) {
        return 0;
    }
    return AutomotiveBus_Stream_Pdu_DoIpMetadata_end(B);
}

static AutomotiveBus_Stream_Pdu_DoIpMetadata_ref_t AutomotiveBus_Stream_Pdu_DoIpMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_DoIpMetadata_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (AutomotiveBus_Stream_Pdu_DoIpMetadata_start(B)
        || AutomotiveBus_Stream_Pdu_DoIpMetadata_payload_type_pick(B, t)
        || AutomotiveBus_Stream_Pdu_DoIpMetadata_protocol_version_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, AutomotiveBus_Stream_Pdu_DoIpMetadata_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, AutomotiveBus_Stream_Pdu_SomeIpMetadata_message_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), AutomotiveBus_Stream_Pdu_SomeIpMetadata)
__flatbuffers_build_scalar_field(1, flatbuffers_, AutomotiveBus_Stream_Pdu_SomeIpMetadata_length, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), AutomotiveBus_Stream_Pdu_SomeIpMetadata)
__flatbuffers_build_scalar_field(2, flatbuffers_, AutomotiveBus_Stream_Pdu_SomeIpMetadata_request_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), AutomotiveBus_Stream_Pdu_SomeIpMetadata)
__flatbuffers_build_scalar_field(3, flatbuffers_, AutomotiveBus_Stream_Pdu_SomeIpMetadata_protocol_version, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), AutomotiveBus_Stream_Pdu_SomeIpMetadata)
__flatbuffers_build_scalar_field(4, flatbuffers_, AutomotiveBus_Stream_Pdu_SomeIpMetadata_interface_version, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), AutomotiveBus_Stream_Pdu_SomeIpMetadata)
__flatbuffers_build_scalar_field(5, flatbuffers_, AutomotiveBus_Stream_Pdu_SomeIpMetadata_message_type, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), AutomotiveBus_Stream_Pdu_SomeIpMetadata)
__flatbuffers_build_scalar_field(6, flatbuffers_, AutomotiveBus_Stream_Pdu_SomeIpMetadata_return_code, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), AutomotiveBus_Stream_Pdu_SomeIpMetadata)

static inline AutomotiveBus_Stream_Pdu_SomeIpMetadata_ref_t AutomotiveBus_Stream_Pdu_SomeIpMetadata_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_SomeIpMetadata_formal_args)
{
    if (AutomotiveBus_Stream_Pdu_SomeIpMetadata_start(B)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_message_id_add(B, v0)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_length_add(B, v1)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_request_id_add(B, v2)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_protocol_version_add(B, v3)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_interface_version_add(B, v4)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_message_type_add(B, v5)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_return_code_add(B, v6)) {
        return 0;
    }
    return AutomotiveBus_Stream_Pdu_SomeIpMetadata_end(B);
}

static AutomotiveBus_Stream_Pdu_SomeIpMetadata_ref_t AutomotiveBus_Stream_Pdu_SomeIpMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_SomeIpMetadata_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (AutomotiveBus_Stream_Pdu_SomeIpMetadata_start(B)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_message_id_pick(B, t)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_length_pick(B, t)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_request_id_pick(B, t)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_protocol_version_pick(B, t)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_interface_version_pick(B, t)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_message_type_pick(B, t)
        || AutomotiveBus_Stream_Pdu_SomeIpMetadata_return_code_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, AutomotiveBus_Stream_Pdu_SomeIpMetadata_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, AutomotiveBus_Stream_Pdu_IpV4_src_addr, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), AutomotiveBus_Stream_Pdu_IpV4)
__flatbuffers_build_scalar_field(1, flatbuffers_, AutomotiveBus_Stream_Pdu_IpV4_dst_addr, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), AutomotiveBus_Stream_Pdu_IpV4)

static inline AutomotiveBus_Stream_Pdu_IpV4_ref_t AutomotiveBus_Stream_Pdu_IpV4_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_IpV4_formal_args)
{
    if (AutomotiveBus_Stream_Pdu_IpV4_start(B)
        || AutomotiveBus_Stream_Pdu_IpV4_src_addr_add(B, v0)
        || AutomotiveBus_Stream_Pdu_IpV4_dst_addr_add(B, v1)) {
        return 0;
    }
    return AutomotiveBus_Stream_Pdu_IpV4_end(B);
}

static AutomotiveBus_Stream_Pdu_IpV4_ref_t AutomotiveBus_Stream_Pdu_IpV4_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_IpV4_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (AutomotiveBus_Stream_Pdu_IpV4_start(B)
        || AutomotiveBus_Stream_Pdu_IpV4_src_addr_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpV4_dst_addr_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, AutomotiveBus_Stream_Pdu_IpV4_end(B));
}

__flatbuffers_build_struct_field(0, flatbuffers_, AutomotiveBus_Stream_Pdu_IpV6_src_addr, AutomotiveBus_Stream_Pdu_IpAddressV6, 16, 2, AutomotiveBus_Stream_Pdu_IpV6)
__flatbuffers_build_struct_field(1, flatbuffers_, AutomotiveBus_Stream_Pdu_IpV6_dst_addr, AutomotiveBus_Stream_Pdu_IpAddressV6, 16, 2, AutomotiveBus_Stream_Pdu_IpV6)

static inline AutomotiveBus_Stream_Pdu_IpV6_ref_t AutomotiveBus_Stream_Pdu_IpV6_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_IpV6_formal_args)
{
    if (AutomotiveBus_Stream_Pdu_IpV6_start(B)
        || AutomotiveBus_Stream_Pdu_IpV6_src_addr_add(B, v0)
        || AutomotiveBus_Stream_Pdu_IpV6_dst_addr_add(B, v1)) {
        return 0;
    }
    return AutomotiveBus_Stream_Pdu_IpV6_end(B);
}

static AutomotiveBus_Stream_Pdu_IpV6_ref_t AutomotiveBus_Stream_Pdu_IpV6_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_IpV6_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (AutomotiveBus_Stream_Pdu_IpV6_start(B)
        || AutomotiveBus_Stream_Pdu_IpV6_src_addr_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpV6_dst_addr_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, AutomotiveBus_Stream_Pdu_IpV6_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_dst_mac, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_scalar_field(1, flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_src_mac, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_scalar_field(2, flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_ethertype, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_scalar_field(3, flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_tci_pcp, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_scalar_field(4, flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_tci_dei, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_scalar_field(5, flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_tci_vid, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_union_field(7, flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_addr, AutomotiveBus_Stream_Pdu_IpAddr, AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_union_table_value_field(flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_addr, AutomotiveBus_Stream_Pdu_IpAddr, v4, AutomotiveBus_Stream_Pdu_IpV4)
__flatbuffers_build_union_table_value_field(flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_addr, AutomotiveBus_Stream_Pdu_IpAddr, v6, AutomotiveBus_Stream_Pdu_IpV6)
__flatbuffers_build_scalar_field(8, flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_protocol, AutomotiveBus_Stream_Pdu_IpProtocol, AutomotiveBus_Stream_Pdu_IpProtocol_enum_t, 1, 1, UINT8_C(0), AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_scalar_field(9, flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_src_port, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_scalar_field(10, flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_dst_port, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_union_field(12, flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_adapter, AutomotiveBus_Stream_Pdu_SocketAdapter, AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_union_table_value_field(flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_adapter, AutomotiveBus_Stream_Pdu_SocketAdapter, do_ip, AutomotiveBus_Stream_Pdu_DoIpMetadata)
__flatbuffers_build_union_table_value_field(flatbuffers_, AutomotiveBus_Stream_Pdu_IpMessageMetadata_adapter, AutomotiveBus_Stream_Pdu_SocketAdapter, some_ip, AutomotiveBus_Stream_Pdu_SomeIpMetadata)

static inline AutomotiveBus_Stream_Pdu_IpMessageMetadata_ref_t AutomotiveBus_Stream_Pdu_IpMessageMetadata_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_IpMessageMetadata_formal_args)
{
    if (AutomotiveBus_Stream_Pdu_IpMessageMetadata_start(B)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_dst_mac_add(B, v0)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_src_mac_add(B, v1)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_addr_add_value(B, v7)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_adapter_add_value(B, v12)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_ethertype_add(B, v2)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_tci_vid_add(B, v5)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_src_port_add(B, v9)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_dst_port_add(B, v10)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_tci_pcp_add(B, v3)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_tci_dei_add(B, v4)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_protocol_add(B, v8)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_addr_add_type(B, v7.type)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_adapter_add_type(B, v12.type)) {
        return 0;
    }
    return AutomotiveBus_Stream_Pdu_IpMessageMetadata_end(B);
}

static AutomotiveBus_Stream_Pdu_IpMessageMetadata_ref_t AutomotiveBus_Stream_Pdu_IpMessageMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_IpMessageMetadata_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (AutomotiveBus_Stream_Pdu_IpMessageMetadata_start(B)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_dst_mac_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_src_mac_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_addr_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_adapter_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_ethertype_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_tci_vid_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_src_port_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_dst_port_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_tci_pcp_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_eth_tci_dei_pick(B, t)
        || AutomotiveBus_Stream_Pdu_IpMessageMetadata_ip_protocol_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, AutomotiveBus_Stream_Pdu_IpMessageMetadata_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, AutomotiveBus_Stream_Pdu_StructMetadata_type_name, AutomotiveBus_Stream_Pdu_StructMetadata)
__flatbuffers_build_string_field(1, flatbuffers_, AutomotiveBus_Stream_Pdu_StructMetadata_var_name, AutomotiveBus_Stream_Pdu_StructMetadata)
__flatbuffers_build_string_field(2, flatbuffers_, AutomotiveBus_Stream_Pdu_StructMetadata_encoding, AutomotiveBus_Stream_Pdu_StructMetadata)
__flatbuffers_build_scalar_field(3, flatbuffers_, AutomotiveBus_Stream_Pdu_StructMetadata_attribute_aligned, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), AutomotiveBus_Stream_Pdu_StructMetadata)
__flatbuffers_build_scalar_field(4, flatbuffers_, AutomotiveBus_Stream_Pdu_StructMetadata_attribute_packed, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), AutomotiveBus_Stream_Pdu_StructMetadata)
__flatbuffers_build_string_field(5, flatbuffers_, AutomotiveBus_Stream_Pdu_StructMetadata_platform_arch, AutomotiveBus_Stream_Pdu_StructMetadata)
__flatbuffers_build_string_field(6, flatbuffers_, AutomotiveBus_Stream_Pdu_StructMetadata_platform_os, AutomotiveBus_Stream_Pdu_StructMetadata)
__flatbuffers_build_string_field(7, flatbuffers_, AutomotiveBus_Stream_Pdu_StructMetadata_platform_abi, AutomotiveBus_Stream_Pdu_StructMetadata)

static inline AutomotiveBus_Stream_Pdu_StructMetadata_ref_t AutomotiveBus_Stream_Pdu_StructMetadata_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_StructMetadata_formal_args)
{
    if (AutomotiveBus_Stream_Pdu_StructMetadata_start(B)
        || AutomotiveBus_Stream_Pdu_StructMetadata_type_name_add(B, v0)
        || AutomotiveBus_Stream_Pdu_StructMetadata_var_name_add(B, v1)
        || AutomotiveBus_Stream_Pdu_StructMetadata_encoding_add(B, v2)
        || AutomotiveBus_Stream_Pdu_StructMetadata_platform_arch_add(B, v5)
        || AutomotiveBus_Stream_Pdu_StructMetadata_platform_os_add(B, v6)
        || AutomotiveBus_Stream_Pdu_StructMetadata_platform_abi_add(B, v7)
        || AutomotiveBus_Stream_Pdu_StructMetadata_attribute_aligned_add(B, v3)
        || AutomotiveBus_Stream_Pdu_StructMetadata_attribute_packed_add(B, v4)) {
        return 0;
    }
    return AutomotiveBus_Stream_Pdu_StructMetadata_end(B);
}

static AutomotiveBus_Stream_Pdu_StructMetadata_ref_t AutomotiveBus_Stream_Pdu_StructMetadata_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_StructMetadata_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (AutomotiveBus_Stream_Pdu_StructMetadata_start(B)
        || AutomotiveBus_Stream_Pdu_StructMetadata_type_name_pick(B, t)
        || AutomotiveBus_Stream_Pdu_StructMetadata_var_name_pick(B, t)
        || AutomotiveBus_Stream_Pdu_StructMetadata_encoding_pick(B, t)
        || AutomotiveBus_Stream_Pdu_StructMetadata_platform_arch_pick(B, t)
        || AutomotiveBus_Stream_Pdu_StructMetadata_platform_os_pick(B, t)
        || AutomotiveBus_Stream_Pdu_StructMetadata_platform_abi_pick(B, t)
        || AutomotiveBus_Stream_Pdu_StructMetadata_attribute_aligned_pick(B, t)
        || AutomotiveBus_Stream_Pdu_StructMetadata_attribute_packed_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, AutomotiveBus_Stream_Pdu_StructMetadata_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, AutomotiveBus_Stream_Pdu_Pdu_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), AutomotiveBus_Stream_Pdu_Pdu)
__flatbuffers_build_vector_field(1, flatbuffers_, AutomotiveBus_Stream_Pdu_Pdu_payload, flatbuffers_uint8, uint8_t, AutomotiveBus_Stream_Pdu_Pdu)
__flatbuffers_build_union_field(3, flatbuffers_, AutomotiveBus_Stream_Pdu_Pdu_transport, AutomotiveBus_Stream_Pdu_TransportMetadata, AutomotiveBus_Stream_Pdu_Pdu)
__flatbuffers_build_union_table_value_field(flatbuffers_, AutomotiveBus_Stream_Pdu_Pdu_transport, AutomotiveBus_Stream_Pdu_TransportMetadata, Can, AutomotiveBus_Stream_Pdu_CanMessageMetadata)
__flatbuffers_build_union_table_value_field(flatbuffers_, AutomotiveBus_Stream_Pdu_Pdu_transport, AutomotiveBus_Stream_Pdu_TransportMetadata, Ip, AutomotiveBus_Stream_Pdu_IpMessageMetadata)
__flatbuffers_build_union_table_value_field(flatbuffers_, AutomotiveBus_Stream_Pdu_Pdu_transport, AutomotiveBus_Stream_Pdu_TransportMetadata, Struct, AutomotiveBus_Stream_Pdu_StructMetadata)
__flatbuffers_build_scalar_field(4, flatbuffers_, AutomotiveBus_Stream_Pdu_Pdu_swc_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), AutomotiveBus_Stream_Pdu_Pdu)
__flatbuffers_build_scalar_field(5, flatbuffers_, AutomotiveBus_Stream_Pdu_Pdu_ecu_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), AutomotiveBus_Stream_Pdu_Pdu)

static inline AutomotiveBus_Stream_Pdu_Pdu_ref_t AutomotiveBus_Stream_Pdu_Pdu_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_Pdu_formal_args)
{
    if (AutomotiveBus_Stream_Pdu_Pdu_start(B)
        || AutomotiveBus_Stream_Pdu_Pdu_id_add(B, v0)
        || AutomotiveBus_Stream_Pdu_Pdu_payload_add(B, v1)
        || AutomotiveBus_Stream_Pdu_Pdu_transport_add_value(B, v3)
        || AutomotiveBus_Stream_Pdu_Pdu_swc_id_add(B, v4)
        || AutomotiveBus_Stream_Pdu_Pdu_ecu_id_add(B, v5)
        || AutomotiveBus_Stream_Pdu_Pdu_transport_add_type(B, v3.type)) {
        return 0;
    }
    return AutomotiveBus_Stream_Pdu_Pdu_end(B);
}

static AutomotiveBus_Stream_Pdu_Pdu_ref_t AutomotiveBus_Stream_Pdu_Pdu_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_Pdu_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (AutomotiveBus_Stream_Pdu_Pdu_start(B)
        || AutomotiveBus_Stream_Pdu_Pdu_id_pick(B, t)
        || AutomotiveBus_Stream_Pdu_Pdu_payload_pick(B, t)
        || AutomotiveBus_Stream_Pdu_Pdu_transport_pick(B, t)
        || AutomotiveBus_Stream_Pdu_Pdu_swc_id_pick(B, t)
        || AutomotiveBus_Stream_Pdu_Pdu_ecu_id_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, AutomotiveBus_Stream_Pdu_Pdu_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, AutomotiveBus_Stream_Pdu_Stream_pdus, AutomotiveBus_Stream_Pdu_Pdu, AutomotiveBus_Stream_Pdu_Stream)
__flatbuffers_build_scalar_field(1, flatbuffers_, AutomotiveBus_Stream_Pdu_Stream_node_uid, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), AutomotiveBus_Stream_Pdu_Stream)

static inline AutomotiveBus_Stream_Pdu_Stream_ref_t AutomotiveBus_Stream_Pdu_Stream_create(flatbuffers_builder_t *B __AutomotiveBus_Stream_Pdu_Stream_formal_args)
{
    if (AutomotiveBus_Stream_Pdu_Stream_start(B)
        || AutomotiveBus_Stream_Pdu_Stream_pdus_add(B, v0)
        || AutomotiveBus_Stream_Pdu_Stream_node_uid_add(B, v1)) {
        return 0;
    }
    return AutomotiveBus_Stream_Pdu_Stream_end(B);
}

static AutomotiveBus_Stream_Pdu_Stream_ref_t AutomotiveBus_Stream_Pdu_Stream_clone(flatbuffers_builder_t *B, AutomotiveBus_Stream_Pdu_Stream_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (AutomotiveBus_Stream_Pdu_Stream_start(B)
        || AutomotiveBus_Stream_Pdu_Stream_pdus_pick(B, t)
        || AutomotiveBus_Stream_Pdu_Stream_node_uid_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, AutomotiveBus_Stream_Pdu_Stream_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* PDU_BUILDER_H */
