# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Pdu

class CanFrameType(object):
    # CAN Data Frame.
    DataFrame = 0
    # CAN Remote Frame.
    RemoteFrame = 1
    # CAN Error Frame.
    ErrorFrame = 2
    # CAN Overload Frame.
    OverloadFrame = 3

