# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Pdu

class CanMessageFormat(object):
    # CAN Base Format (pdu.id is 11-bits).
    BaseFrameFormat = 0
    # CAN Extended Format (pdu.id is 29-bits).
    ExtendedFrameFormat = 1
    # CAN FD Base Format (pdu.id is 11-bits).
    FdBaseFrameFormat = 2
    # CAN FD Extended Format (pdu.id is 29-bits).
    FdExtendedFrameFormat = 3

