# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Pdu

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IpV4(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IpV4()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIpV4(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def IpV4BufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x50\x44\x55", size_prefixed=size_prefixed)

    # IpV4
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IpV4
    def SrcAddr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # IpV4
    def DstAddr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(2)
def IpV4Start(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddSrcAddr(builder, srcAddr): builder.PrependUint32Slot(0, srcAddr, 0)
def IpV4AddSrcAddr(builder, srcAddr):
    """This method is deprecated. Please switch to AddSrcAddr."""
    return AddSrcAddr(builder, srcAddr)
def AddDstAddr(builder, dstAddr): builder.PrependUint32Slot(1, dstAddr, 0)
def IpV4AddDstAddr(builder, dstAddr):
    """This method is deprecated. Please switch to AddDstAddr."""
    return AddDstAddr(builder, dstAddr)
def End(builder): return builder.EndObject()
def IpV4End(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)