# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Pdu

class SocketAdapter(object):
    NONE = 0
    # DoIp: Diagnostic Communication over Internet Protocol.
    do_ip = 1
    # Some/IP: Scalable service-Oriented Midedleware over IP.
    some_ip = 2

