# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlexRay

class FrameIndicatorBits(object):
    Startup = 1
    Sync = 2
    NotNull = 4
    Payload = 8
    Reserved = 16

