# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Can

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CanStatus(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CanStatus()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCanStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CanStatusBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x52\x49\x43\x41", size_prefixed=size_prefixed)

    # CanStatus
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CanStatus
    def Sync(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 1

def Start(builder): builder.StartObject(1)
def CanStatusStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddSync(builder, sync): builder.PrependInt8Slot(0, sync, 1)
def CanStatusAddSync(builder, sync):
    """This method is deprecated. Please switch to AddSync."""
    return AddSync(builder, sync)
def End(builder): return builder.EndObject()
def CanStatusEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)